import type { BrowserContext } from "@playwright/test";
import { promises as fs } from "node:fs";
import path from "node:path";

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

async function writePreviewImage(
  page: Awaited<ReturnType<BrowserContext["newPage"]>>,
  filePath: string,
  payload: {
    accent: string;
    eyebrow: string;
    title: string;
    subtitle: string;
    note: string;
  },
) {
  await page.setViewportSize({ width: 1280, height: 1600 });
  await page.setContent(`
    <html>
      <head>
        <style>
          html, body {
            margin: 0;
            width: 100%;
            height: 100%;
            background: radial-gradient(circle at top left, #1a1a16, #0b0b09 70%);
            font-family: Arial, Helvetica, sans-serif;
          }
          .card {
            box-sizing: border-box;
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 80px;
            color: #f5f0e8;
            border: 18px solid ${payload.accent};
          }
          .eyebrow {
            font-size: 48px;
            letter-spacing: 0.24em;
            text-transform: uppercase;
            color: ${payload.accent};
          }
          h1 {
            margin: 0;
            font-size: 120px;
            line-height: 0.9;
            max-width: 10ch;
          }
          .copy {
            max-width: 720px;
            display: grid;
            gap: 24px;
          }
          .subtitle {
            font-size: 40px;
            line-height: 1.2;
            color: #d7cab5;
          }
          .note {
            font-size: 32px;
            color: #c4b7a0;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <div class="eyebrow">${escapeHtml(payload.eyebrow)}</div>
          <div class="copy">
            <h1>${escapeHtml(payload.title)}</h1>
            <div class="subtitle">${escapeHtml(payload.subtitle)}</div>
          </div>
          <div class="note">${escapeHtml(payload.note)}</div>
        </div>
      </body>
    </html>
  `);
  await page.screenshot({ path: filePath, fullPage: true });
}

export async function createSmokeImageFixtures(context: BrowserContext, directory: string) {
  await fs.mkdir(directory, { recursive: true });
  const page = await context.newPage();

  try {
    const productImage = path.join(directory, "product.png");
    const shopeeScreenshot = path.join(directory, "shopee.png");
    const tiktokScreenshot = path.join(directory, "tiktok.png");

    await writePreviewImage(page, productImage, {
      accent: "#d8b46a",
      eyebrow: "Product",
      title: "Smoke Product",
      subtitle: "Primary product reference for intake analysis.",
      note: "Generated by Playwright smoke test.",
    });
    await writePreviewImage(page, shopeeScreenshot, {
      accent: "#7fb069",
      eyebrow: "Shopee",
      title: "Marketplace Proof",
      subtitle: "Reference screenshot for store context.",
      note: "Used for live intake upload.",
    });
    await writePreviewImage(page, tiktokScreenshot, {
      accent: "#6cc5ff",
      eyebrow: "TikTok",
      title: "Short Video Proof",
      subtitle: "Reference screenshot for social context.",
      note: "Used for live intake upload.",
    });

    return {
      productImage,
      shopeeScreenshot,
      tiktokScreenshot,
    };
  } finally {
    await page.close();
  }
}

